# Caffe2 基本概念 - Workspace

在这个教程中，我们将学习一些Caffe2的基本概念：workspace。

首先，让我们导入caffe2的 `core` 和 `workspace`，这两项是你最需要的。如果你想操作由Caffe2生成的协议缓冲区，你也需要从caffe2.proto导入caffe2_pb2。

In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

# 导入一些标准库
from matplotlib import pyplot
import numpy as np
import time

# Fof Caffe2
from caffe2.python import core, workspace
from caffe2.proto import caffe2_pb2

%matplotlib inline

## Workspaces

In [2]:
print("Current blobs in the workspace: {}".format(workspace.Blobs()))
print("Workspace has blob 'X'? {}".format(workspace.HasBlob("X")))

Current blobs in the workspace: []
Workspace has blob 'X'? False


我们可以使用FeedBlob()把blobs送入workspace。

In [3]:
X = np.random.randn(2, 3).astype(np.float32)
print("Generated X from numpy:\n{}".format(X))
workspace.FeedBlob("X", X)

Generated X from numpy:
[[ 0.53093946  0.3100414  -0.04606299]
 [-0.2087793   0.19440559 -0.10280976]]


True

使用FetchBlobs()获取Blob。

In [4]:
print("Current blobs in the workspace: {}".format(workspace.Blobs()))
print("Workspace has blob 'X'? {}".format(workspace.HasBlob("X")))
print("Fetched X:\n{}".format(workspace.FetchBlob("X")))

Current blobs in the workspace: [u'X']
Workspace has blob 'X'? True
Fetched X:
[[ 0.53093946  0.3100414  -0.04606299]
 [-0.2087793   0.19440559 -0.10280976]]


我们验证一下数组是否相等。

In [5]:
np.testing.assert_array_equal(X, workspace.FetchBlob("X"))

In [6]:
try:
    workspace.FetchBlob("invincible_pink_unicorn")
except RuntimeError as err:
    print(err)

[enforce fail at pybind_state.cc:174] ws->HasBlob(name). Can't find blob: invincible_pink_unicorn 


你可以在Python中使用不同名称的多个工作空间，并在它们之间切换。 不同工作区中的Blob彼此分离。 您可以使用`CurrentWorkspace`查询当前工作空间。 让我们尝试按名称（gutentag）切换工作区，如果它不存在，则创建一个新工作区。

打印当前workspace空间名称。当存在多个workspace时，使用SwitchWorkspace()转换当前空间。

In [7]:
print("Current workspace: {}".format(workspace.CurrentWorkspace()))
print("Current blobs in the workspace: {}".format(workspace.Blobs()))

# Switch the workspace. The second argument "True" means creating 
# the workspace if it is missing.
workspace.SwitchWorkspace("gutentag", True)

# Let's print the current workspace. Note that there is nothing in the
# workspace yet.
print("Current workspace: {}".format(workspace.CurrentWorkspace()))
print("Current blobs in the workspace: {}".format(workspace.Blobs()))

Current workspace: default
Current blobs in the workspace: [u'X']
Current workspace: gutentag
Current blobs in the workspace: []


让我们更改回默认workspace。

In [8]:
workspace.SwitchWorkspace("default")
print("Current workspace: {}".format(workspace.CurrentWorkspace()))
print("Current blobs in the workspace: {}".format(workspace.Blobs()))

Current workspace: default
Current blobs in the workspace: [u'X']


最后使用`ResetWorkspace()`清理当前空间。

In [9]:
workspace.ResetWorkspace()
print("Current blobs in the workspace after reset: {}".format(workspace.Blobs()))

Current blobs in the workspace after reset: []
